use customer_behavior;
RENAME TABLE table1 to  users;
SELECT * FROM users LIMIT 5;

-- Q1. What is the total revenue generated by male vs. female customers? 
SELECT gender as Gender,SUM(purchase_amount) as Total_Revenue FROM users
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id , purchase_amount AS Spented_Money FROM users
where discount_applied = 'Yes' and purchase_amount > (SELECT AVG(purchase_amount) FROM users);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased as Product, round(AVG(review_rating),2) as 'Average Product Rating' FROM users
group by item_purchased
order by round(AVG(review_rating),2) desc;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type AS Shipping , AVG(purchase_amount) AS Avg_Price_MONEY FROM users
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT subscription_status , 
count(subscription_status) AS total_subscription, 
round(AVG(purchase_amount),2) AS avg_spend , 
round(SUM(purchase_amount),2) AS total_of_revenue FROM users
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM users
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

WITH customer_type as (
 select customer_id , previous_purchases ,
 CASE 
  WHEN previous_purchases = 1 THEN 'NEW'
  WHEN previous_purchases BETWEEN 2 AND 10 THEN ' Returning'
  ELSE 'Loyel'
  END AS 'Segment'
 from users)

SELECT Segment , count(*) as No_of_Customers FROM customer_type 
GROUP BY Segment;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_count as(
 SELECT category , item_purchased , count(customer_id) as 'total_order' ,
 ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank  FROM users
 GROUP BY category, item_purchased order by category,total_order desc)
 
SELECT * FROM item_count WHERE item_rank <= 3; 

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT count(customer_id) as 'repeat buyers' , subscription_status  FROM users 
WHERE previous_purchases > 5 
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group? 

SELECT age_group , SUM(purchase_amount) AS 'Total_Revanue' FROM users
GROUP BY age_group
ORDER BY Total_Revanue desc;